### ISSUE TITLE
There is no AIEasy

### ISSUE THREAD

**Issue by KC-T1** [pielegacy/battleship#15]

**Comment by KC-T1** [comment]
Anyone who wants to handle this must mark it in trello.
If there is no one who do it after I finish my part, I will probably do it

**Comment by notahumanbeingatthismoment** [comment]
What is AI Easy?

**Comment by KC-T1** [comment]
It's just the enemy difficulties
U have to create AI with difficulty of easy.
There is a note in the code as well of how AI easy should do.
Read it and write the code for AI Easy model

**Comment by KC-T1** [comment]
OK.
it is fixed
Please test it anyone.

**Comment by KC-T1** [comment]
Oh I add the setting that EASy is default.

**Comment by pielegacy** [comment]
Has been tested, definitely closed
