### ISSUE TITLE
Problem rotating the ships in the deployment phase of the game

### ISSUE THREAD

**Issue by emperorjun** [pielegacy/battleship#2]
once rotated to the horizontal column. it wont rotate back to the vertical column.
This issue is probably due to the vertical rotate button being un-clickable/inactive

**Comment by emperorjun** [comment]
once rotated to the horizontal column. it wont rotate back to the vertical column

**Comment by KC-T1** [comment]
it's done.
See the commit at the csharp-battleship-setup-bug

**Comment by KC-T1** [comment]
Please test it and close this issue
