### ISSUE TITLE
Game abruptly went to the main menu when player lose the game

### ISSUE THREAD

**Issue by emperorjun** [pielegacy/battleship#4]
There is no notification such as "you are defeated" or etc.
not sure if there is a bug or if the feature is simply not implemented yet.

**Comment by KC-T1** [comment]
It's a bug.
I see the code comment in the EndingGameController that it must show lose or win at the end of each game

**Comment by KC-T1** [comment]
There is a Lose sign after the end game but the process into that always create a delay to the point of NOT RESPONDING shown as we often get impatient we will click it continuously despite that and thus we skip the lose sign
Therefore this is Enhancement rather than bug
