### ISSUE TITLE
Tell the user that pressing [ESC] access the main menu during game

### ISSUE THREAD

**Issue by emperorjun** [pielegacy/battleship#7]

**Comment by pielegacy** [comment]
![image](https://cloud.githubusercontent.com/assets/7465061/25205350/6c203bac-25a5-11e7-9e0b-63469eecdb82.png)
Added this simple piece of text to `discover.jpg` changes pushed to `csharp-menu-prompt` branch

**Comment by pielegacy** [comment]
Has been tested
